// Single source of truth for reserved usernames.
// These match app routes, API paths, and common system names
// that must never be registered as user profiles.
export const RESERVED_USERNAMES = [
  // App pages
  "dashboard",
  "auth",
  "demo",
  "pricing",
  "privacy",
  "terms",
  "payment",
  // App sub-routes (reachable via /dashboard/*)
  "settings",
  "analytics",
  "billing",
  "design",
  "login",
  "register",
  "forgot-password",
  "reset-password",
  "callback",
  "success",
  "cancel",
  // API & system
  "api",
  "app",
  "www",
  "_next",
  "favicon.ico",
  "icon.png",
  "robots.txt",
  "sitemap.xml",
  // Brand / common reserved
  "admin",
  "allme",
  "test",
  "user",
  "help",
  "support",
  "about",
  "blog",
  "mail",
  "contact",
  "home",
  "profile",
  "account",
  "signup",
  "signin",
  "logout",
  "feed",
  "explore",
  "search",
  "notifications",
  "messages",
  "status",
  "checkout",
  "webhooks",
  "og",
  "promo",
];
